language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="django>=1.10.0,<1.11.0" REST_FRAMEWORK="djangorestframework>=3.5,<3.6"
  - DJANGO="django>=1.9.0,<1.10.0" REST_FRAMEWORK="djangorestframework>=3.5,<3.6"
  - DJANGO="django>=1.8.0,<1.9.0" REST_FRAMEWORK="djangorestframework>=3.5,<3.6"
  - DJANGO="django>=1.8.0,<1.9.0" REST_FRAMEWORK="djangorestframework>=3.4,<3.5"
install:
  - travis_retry pip install -q $DJANGO $REST_FRAMEWORK "coverage==3.7.1"
  - pip install .
script:
  - coverage run manage.py test
  - coverage report
after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django>=1.10.0,<1.11.0" REST_FRAMEWORK="djangorestframework>=3.5,<3.6"
    - python: "3.3"
      env: DJANGO="django>=1.9.0,<1.10.0" REST_FRAMEWORK="djangorestframework>=3.5,<3.6"
  fast_finish: true
